# Use Ubuntu as the base image
FROM ubuntu:20.04

# Set environment variables to prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive
ENV MACHTYPE=x86_64
ENV PATH=/usr/local/bin:$PATH

# Update and install system dependencies
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    make \
    gcc \
    python3 \
    python3-pip \
    && apt-get clean

# Install Python dependencies
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Install bedtools
RUN apt-get update && apt-get install -y \
    software-properties-common \
    && add-apt-repository universe \
    && apt-get update \
    && apt-get install -y bedtools \
    && apt-get clean

## Install samtools dependencies
RUN apt-get update && apt-get install -y \
    autoconf \
    && apt-get clean

RUN apt-get update && apt-get install -y \
    automake perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev libdeflate-dev \
    && apt-get clean

## Install samtools
RUN wget https://github.com/samtools/samtools/releases/download/1.21/samtools-1.21.tar.bz2 \
    && tar -xjf samtools-1.21.tar.bz2 \
    && rm samtools-1.21.tar.bz2 \
    && cd samtools-1.21 \
    && autoheader \
    && autoconf -Wno-syntax \ 
    && ./configure \
    && make \
    && make install

# Add local Python package (PLP_directRNA_design)
COPY PLP_directRNA_design /app/PLP_directRNA_design

# Expose port 2222 for this container
EXPOSE 2222

# Install Jupyter Notebook
RUN pip3 install notebook

## Set perl locale settings
ENV LC_ALL=C

# Set the working directory
WORKDIR /app

# Start Jupyter Notebook by default
CMD ["bash"]
#CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=2222", "--no-browser", "--allow-root"]